# Generated by Django 4.1.7 on 2023-04-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movieactor',
            table=None,
        ),
    ]
