# Generated by Django 4.1.7 on 2023-04-12 17:37

import django.core.validators
from django.db import migrations, models
import imdb_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0002_alter_movieactor_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_year',
            field=models.IntegerField(db_column='birth_year', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(db_column='year', validators=[django.core.validators.MinValueValidator(1800), imdb_app.validators.validate_year_before_now]),
        ),
        migrations.AlterField(
            model_name='movieactor',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='movieactor',
            table='movie_actors',
        ),
    ]
